### ISSUE TITLE
Add a read-only demo sheet accessible without configuring a Provider

### ISSUE THREAD

**Issue by ryantheleach** [dhleong/wish#135]
I found your project, and it looks promising from the description.

However I can't currently demo it without granting it access to my google drive.

You would gain more use/attention if you provide images / a read only demo that doesn't use google drive.

**Comment by dhleong** [comment]
Hey @ryantheleach thanks for the interest! You're right that a read-only demo would be a great idea, but not sure how soon I'll have time to do that.

For what it's worth, as the login dialog explains, when you initially connect with Google we only have access to files that were created by Wish; we cannot access other files in your Drive. Feel free to peruse the source if you don't trust me—I made everything open source for a reason!

**Comment by dhleong** [comment]
@ryantheleach Sorry it took so long but I recently got on a bit of a roll adding features and fixing issues for a campaign I've been playing, and found the time to set up a couple demo sheets. Here are a couple direct links:

- https://dhleong.github.io/wish/sheets/demo/wmreynolds
- https://dhleong.github.io/wish/sheets/demo/wkatara
